FROM golang:1.26.2 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o tasks .

FROM alpine:latest
WORKDIR /

COPY --from=builder /app/tasks .
COPY --from=builder /app/frontend ./frontend
COPY --from=builder /app/migrations ./migrations

# Создаём non-root пользователя
RUN adduser -D -s /bin/sh appuser
USER appuser
EXPOSE 8080
CMD [ "./tasks" ]
